# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-16 03:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', 'insert_material_colors'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='backgroundImage',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='uploads/images'),
        ),
        migrations.AddField(
            model_name='section',
            name='order',
            field=models.SmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='section',
            name='backgroundColor',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.ColorPrimary'),
        ),
    ]
