# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-13 02:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_page_alias'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='toolbar',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Toolbar'),
        ),
    ]
