# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-17 02:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20170417_0226'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='footer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Footer'),
        ),
    ]
