# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-13 03:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_page_alias'),
    ]

    operations = [
        migrations.AddField(
            model_name='toolbar',
            name='name',
            field=models.CharField(blank=True, default='', help_text='Only visible to you. Use it to manage yours toolbars', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='page',
            name='alias',
            field=models.SlugField(default='', help_text='Will be used as the page URL', max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='page',
            name='toolbar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Toolbar'),
        ),
    ]
