# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-13 19:23
from __future__ import unicode_literals

from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20170413_0321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toolbar',
            name='icon',
            field=imagekit.models.fields.ProcessedImageField(default=None, help_text='The icon should be a square image', null=True, upload_to='uploads/icons'),
        ),
        migrations.AlterField(
            model_name='toolbarlink',
            name='name',
            field=models.CharField(default='', max_length=32),
        ),
    ]
