# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-13 19:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20170413_1923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='shortName',
            field=models.CharField(blank=True, default='', help_text='Short version of the page name', max_length=16, null=True),
        ),
    ]
