# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-13 19:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20170413_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='alias',
            field=models.SlugField(default=None, help_text='Will be used as the page URL', max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='page',
            name='name',
            field=models.CharField(default=None, max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='page',
            name='shortName',
            field=models.CharField(blank=True, default=None, help_text='Short version of the page name', max_length=16, null=True),
        ),
    ]
