# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-15 19:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20170415_1931'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='mainPage',
            field=models.BooleanField(default=False),
        ),
    ]
