# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-15 20:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_page_mainpage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagelink',
            name='color',
            field=models.CharField(choices=[('default', 'Default color'), ('primary', 'Primary color'), ('accent', 'Accent color')], default='primary', max_length=255),
        ),
        migrations.AlterField(
            model_name='sociallink',
            name='color',
            field=models.CharField(choices=[('default', 'Default color'), ('primary', 'Primary color'), ('accent', 'Accent color')], default='primary', max_length=255),
        ),
        migrations.AlterField(
            model_name='toolbarlink',
            name='color',
            field=models.CharField(choices=[('default', 'Default color'), ('primary', 'Primary color'), ('accent', 'Accent color')], default='primary', max_length=255),
        ),
    ]
