# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-15 20:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20170415_2000'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pagelink',
            name='order',
        ),
        migrations.AddField(
            model_name='page',
            name='order',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='pagelink',
            name='color',
            field=models.CharField(choices=[('default', 'Default color'), ('primary', 'Primary color'), ('accent', 'Accent color')], default='default', max_length=255),
        ),
        migrations.AlterField(
            model_name='sociallink',
            name='color',
            field=models.CharField(choices=[('default', 'Default color'), ('primary', 'Primary color'), ('accent', 'Accent color')], default='default', max_length=255),
        ),
        migrations.AlterField(
            model_name='toolbarlink',
            name='color',
            field=models.CharField(choices=[('default', 'Default color'), ('primary', 'Primary color'), ('accent', 'Accent color')], default='default', max_length=255),
        ),
    ]
