# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import migrations


def forwards_func(apps, schema_editor):
    Color = apps.get_model("api", "Color")
    db_alias = schema_editor.connection.alias
    Color.objects.using(db_alias).bulk_create([
        Color(name='red50', value='#ffebee', type='primary'),
        Color(name='red100', value='#ffcdd2', type='primary'),
        Color(name='red200', value='#ef9a9a', type='primary'),
        Color(name='red300', value='#e57373', type='primary'),
        Color(name='red400', value='#ef5350', type='primary'),
        Color(name='red500', value='#f44336', type='primary'),
        Color(name='red600', value='#e53935', type='primary'),
        Color(name='red700', value='#d32f2f', type='primary'),
        Color(name='red800', value='#c62828', type='primary'),
        Color(name='red900', value='#b71c1c', type='primary'),

        Color(name='pink50', value='#fce4ec', type='primary'),
        Color(name='pink100', value='#f8bbd0', type='primary'),
        Color(name='pink200', value='#f48fb1', type='primary'),
        Color(name='pink300', value='#f06292', type='primary'),
        Color(name='pink400', value='#ec407a', type='primary'),
        Color(name='pink500', value='#e91e63', type='primary'),
        Color(name='pink600', value='#d81b60', type='primary'),
        Color(name='pink700', value='#c2185b', type='primary'),
        Color(name='pink800', value='#ad1457', type='primary'),
        Color(name='pink900', value='#880e4f', type='primary'),

        Color(name='purple50', value='#f3e5f5', type='primary'),
        Color(name='purple100', value='#e1bee7', type='primary'),
        Color(name='purple200', value='#ce93d8', type='primary'),
        Color(name='purple300', value='#ba68c8', type='primary'),
        Color(name='purple400', value='#ab47bc', type='primary'),
        Color(name='purple500', value='#9c27b0', type='primary'),
        Color(name='purple600', value='#8e24aa', type='primary'),
        Color(name='purple700', value='#7b1fa2', type='primary'),
        Color(name='purple800', value='#6a1b9a', type='primary'),
        Color(name='purple900', value='#4a148c', type='primary'),

        Color(name='deepPurple50', value='#ede7f6', type='primary'),
        Color(name='deepPurple100', value='#d1c4e9', type='primary'),
        Color(name='deepPurple200', value='#b39ddb', type='primary'),
        Color(name='deepPurple300', value='#9575cd', type='primary'),
        Color(name='deepPurple400', value='#7e57c2', type='primary'),
        Color(name='deepPurple500', value='#673ab7', type='primary'),
        Color(name='deepPurple600', value='#5e35b1', type='primary'),
        Color(name='deepPurple700', value='#512da8', type='primary'),
        Color(name='deepPurple800', value='#4527a0', type='primary'),
        Color(name='deepPurple900', value='#311b92', type='primary'),

        Color(name='indigo50', value='#e8eaf6', type='primary'),
        Color(name='indigo100', value='#c5cae9', type='primary'),
        Color(name='indigo200', value='#9fa8da', type='primary'),
        Color(name='indigo300', value='#7986cb', type='primary'),
        Color(name='indigo400', value='#5c6bc0', type='primary'),
        Color(name='indigo500', value='#3f51b5', type='primary'),
        Color(name='indigo600', value='#3949ab', type='primary'),
        Color(name='indigo700', value='#303f9f', type='primary'),
        Color(name='indigo800', value='#283593', type='primary'),
        Color(name='indigo900', value='#1a237e', type='primary'),

        Color(name='blue50', value='#e3f2fd', type='primary'),
        Color(name='blue100', value='#bbdefb', type='primary'),
        Color(name='blue200', value='#90caf9', type='primary'),
        Color(name='blue300', value='#64b5f6', type='primary'),
        Color(name='blue400', value='#42a5f5', type='primary'),
        Color(name='blue500', value='#2196f3', type='primary'),
        Color(name='blue600', value='#1e88e5', type='primary'),
        Color(name='blue700', value='#1976d2', type='primary'),
        Color(name='blue800', value='#1565c0', type='primary'),
        Color(name='blue900', value='#0d47a1', type='primary'),

        Color(name='lightBlue50', value='#e1f5fe', type='primary'),
        Color(name='lightBlue100', value='#b3e5fc', type='primary'),
        Color(name='lightBlue200', value='#81d4fa', type='primary'),
        Color(name='lightBlue300', value='#4fc3f7', type='primary'),
        Color(name='lightBlue400', value='#29b6f6', type='primary'),
        Color(name='lightBlue500', value='#03a9f4', type='primary'),
        Color(name='lightBlue600', value='#039be5', type='primary'),
        Color(name='lightBlue700', value='#0288d1', type='primary'),
        Color(name='lightBlue800', value='#0277bd', type='primary'),
        Color(name='lightBlue900', value='#01579b', type='primary'),

        Color(name='cyan50', value='#e0f7fa', type='primary'),
        Color(name='cyan100', value='#b2ebf2', type='primary'),
        Color(name='cyan200', value='#80deea', type='primary'),
        Color(name='cyan300', value='#4dd0e1', type='primary'),
        Color(name='cyan400', value='#26c6da', type='primary'),
        Color(name='cyan500', value='#00bcd4', type='primary'),
        Color(name='cyan600', value='#00acc1', type='primary'),
        Color(name='cyan700', value='#0097a7', type='primary'),
        Color(name='cyan800', value='#00838f', type='primary'),
        Color(name='cyan900', value='#006064', type='primary'),

        Color(name='teal50', value='#e0f2f1', type='primary'),
        Color(name='teal100', value='#b2dfdb', type='primary'),
        Color(name='teal200', value='#80cbc4', type='primary'),
        Color(name='teal300', value='#4db6ac', type='primary'),
        Color(name='teal400', value='#26a69a', type='primary'),
        Color(name='teal500', value='#009688', type='primary'),
        Color(name='teal600', value='#00897b', type='primary'),
        Color(name='teal700', value='#00796b', type='primary'),
        Color(name='teal800', value='#00695c', type='primary'),
        Color(name='teal900', value='#004d40', type='primary'),

        Color(name='green50', value='#e8f5e9', type='primary'),
        Color(name='green100', value='#c8e6c9', type='primary'),
        Color(name='green200', value='#a5d6a7', type='primary'),
        Color(name='green300', value='#81c784', type='primary'),
        Color(name='green400', value='#66bb6a', type='primary'),
        Color(name='green500', value='#4caf50', type='primary'),
        Color(name='green600', value='#43a047', type='primary'),
        Color(name='green700', value='#388e3c', type='primary'),
        Color(name='green800', value='#2e7d32', type='primary'),
        Color(name='green900', value='#1b5e20', type='primary'),

        Color(name='lightGreen50', value='#f1f8e9', type='primary'),
        Color(name='lightGreen100', value='#dcedc8', type='primary'),
        Color(name='lightGreen200', value='#c5e1a5', type='primary'),
        Color(name='lightGreen300', value='#aed581', type='primary'),
        Color(name='lightGreen400', value='#9ccc65', type='primary'),
        Color(name='lightGreen500', value='#8bc34a', type='primary'),
        Color(name='lightGreen600', value='#7cb342', type='primary'),
        Color(name='lightGreen700', value='#689f38', type='primary'),
        Color(name='lightGreen800', value='#558b2f', type='primary'),
        Color(name='lightGreen900', value='#33691e', type='primary'),

        Color(name='lime50', value='#f9fbe7', type='primary'),
        Color(name='lime100', value='#f0f4c3', type='primary'),
        Color(name='lime200', value='#e6ee9c', type='primary'),
        Color(name='lime300', value='#dce775', type='primary'),
        Color(name='lime400', value='#d4e157', type='primary'),
        Color(name='lime500', value='#cddc39', type='primary'),
        Color(name='lime600', value='#c0ca33', type='primary'),
        Color(name='lime700', value='#afb42b', type='primary'),
        Color(name='lime800', value='#9e9d24', type='primary'),
        Color(name='lime900', value='#827717', type='primary'),

        Color(name='yellow50', value='#fffde7', type='primary'),
        Color(name='yellow100', value='#fff9c4', type='primary'),
        Color(name='yellow200', value='#fff59d', type='primary'),
        Color(name='yellow300', value='#fff176', type='primary'),
        Color(name='yellow400', value='#ffee58', type='primary'),
        Color(name='yellow500', value='#ffeb3b', type='primary'),
        Color(name='yellow600', value='#fdd835', type='primary'),
        Color(name='yellow700', value='#fbc02d', type='primary'),
        Color(name='yellow800', value='#f9a825', type='primary'),
        Color(name='yellow900', value='#f57f17', type='primary'),

        Color(name='amber50', value='#fff8e1', type='primary'),
        Color(name='amber100', value='#ffecb3', type='primary'),
        Color(name='amber200', value='#ffe082', type='primary'),
        Color(name='amber300', value='#ffd54f', type='primary'),
        Color(name='amber400', value='#ffca28', type='primary'),
        Color(name='amber500', value='#ffc107', type='primary'),
        Color(name='amber600', value='#ffb300', type='primary'),
        Color(name='amber700', value='#ffa000', type='primary'),
        Color(name='amber800', value='#ff8f00', type='primary'),
        Color(name='amber900', value='#ff6f00', type='primary'),

        Color(name='orange50', value='#fff3e0', type='primary'),
        Color(name='orange100', value='#ffe0b2', type='primary'),
        Color(name='orange200', value='#ffcc80', type='primary'),
        Color(name='orange300', value='#ffb74d', type='primary'),
        Color(name='orange400', value='#ffa726', type='primary'),
        Color(name='orange500', value='#ff9800', type='primary'),
        Color(name='orange600', value='#fb8c00', type='primary'),
        Color(name='orange700', value='#f57c00', type='primary'),
        Color(name='orange800', value='#ef6c00', type='primary'),
        Color(name='orange900', value='#e65100', type='primary'),

        Color(name='deepOrange50', value='#fbe9e7', type='primary'),
        Color(name='deepOrange100', value='#ffccbc', type='primary'),
        Color(name='deepOrange200', value='#ffab91', type='primary'),
        Color(name='deepOrange300', value='#ff8a65', type='primary'),
        Color(name='deepOrange400', value='#ff7043', type='primary'),
        Color(name='deepOrange500', value='#ff5722', type='primary'),
        Color(name='deepOrange600', value='#f4511e', type='primary'),
        Color(name='deepOrange700', value='#e64a19', type='primary'),
        Color(name='deepOrange800', value='#d84315', type='primary'),
        Color(name='deepOrange900', value='#bf360c', type='primary'),

        Color(name='brown50', value='#efebe9', type='primary'),
        Color(name='brown100', value='#d7ccc8', type='primary'),
        Color(name='brown200', value='#bcaaa4', type='primary'),
        Color(name='brown300', value='#a1887f', type='primary'),
        Color(name='brown400', value='#8d6e63', type='primary'),
        Color(name='brown500', value='#795548', type='primary'),
        Color(name='brown600', value='#6d4c41', type='primary'),
        Color(name='brown700', value='#5d4037', type='primary'),
        Color(name='brown800', value='#4e342e', type='primary'),
        Color(name='brown900', value='#3e2723', type='primary'),

        Color(name='blueGrey50', value='#eceff1', type='primary'),
        Color(name='blueGrey100', value='#cfd8dc', type='primary'),
        Color(name='blueGrey200', value='#b0bec5', type='primary'),
        Color(name='blueGrey300', value='#90a4ae', type='primary'),
        Color(name='blueGrey400', value='#78909c', type='primary'),
        Color(name='blueGrey500', value='#607d8b', type='primary'),
        Color(name='blueGrey600', value='#546e7a', type='primary'),
        Color(name='blueGrey700', value='#455a64', type='primary'),
        Color(name='blueGrey800', value='#37474f', type='primary'),
        Color(name='blueGrey900', value='#263238', type='primary'),

        Color(name='grey50', value='#fafafa', type='primary'),
        Color(name='grey100', value='#f5f5f5', type='primary'),
        Color(name='grey200', value='#eeeeee', type='primary'),
        Color(name='grey300', value='#e0e0e0', type='primary'),
        Color(name='grey400', value='#bdbdbd', type='primary'),
        Color(name='grey500', value='#9e9e9e', type='primary'),
        Color(name='grey600', value='#757575', type='primary'),
        Color(name='grey700', value='#616161', type='primary'),
        Color(name='grey800', value='#424242', type='primary'),
        Color(name='grey900', value='#212121', type='primary'),

        Color(name='black', value='#000000', type='primary'),
        Color(name='white', value='#ffffff', type='primary'),

        # Accent colors
        Color(name='redA100', value='#ff8a80', type='accent'),
        Color(name='redA200', value='#ff5252', type='accent'),
        Color(name='redA400', value='#ff1744', type='accent'),
        Color(name='redA700', value='#d50000', type='accent'),

        Color(name='pinkA100', value='#ff80ab', type='accent'),
        Color(name='pinkA200', value='#ff4081', type='accent'),
        Color(name='pinkA400', value='#f50057', type='accent'),
        Color(name='pinkA700', value='#c51162', type='accent'),

        Color(name='purpleA100', value='#ea80fc', type='accent'),
        Color(name='purpleA200', value='#e040fb', type='accent'),
        Color(name='purpleA400', value='#d500f9', type='accent'),
        Color(name='purpleA700', value='#aa00ff', type='accent'),

        Color(name='deepPurpleA100', value='#b388ff', type='accent'),
        Color(name='deepPurpleA200', value='#7c4dff', type='accent'),
        Color(name='deepPurpleA400', value='#651fff', type='accent'),
        Color(name='deepPurpleA700', value='#6200ea', type='accent'),

        Color(name='indigoA100', value='#8c9eff', type='accent'),
        Color(name='indigoA200', value='#536dfe', type='accent'),
        Color(name='indigoA400', value='#3d5afe', type='accent'),
        Color(name='indigoA700', value='#304ffe', type='accent'),

        Color(name='blueA100', value='#82b1ff', type='accent'),
        Color(name='blueA200', value='#448aff', type='accent'),
        Color(name='blueA400', value='#2979ff', type='accent'),
        Color(name='blueA700', value='#2962ff', type='accent'),

        Color(name='lightBlueA100', value='#80d8ff', type='accent'),
        Color(name='lightBlueA200', value='#40c4ff', type='accent'),
        Color(name='lightBlueA400', value='#00b0ff', type='accent'),
        Color(name='lightBlueA700', value='#0091ea', type='accent'),

        Color(name='cyanA100', value='#84ffff', type='accent'),
        Color(name='cyanA200', value='#18ffff', type='accent'),
        Color(name='cyanA400', value='#00e5ff', type='accent'),
        Color(name='cyanA700', value='#00b8d4', type='accent'),

        Color(name='tealA100', value='#a7ffeb', type='accent'),
        Color(name='tealA200', value='#64ffda', type='accent'),
        Color(name='tealA400', value='#1de9b6', type='accent'),
        Color(name='tealA700', value='#00bfa5', type='accent'),

        Color(name='greenA100', value='#b9f6ca', type='accent'),
        Color(name='greenA200', value='#69f0ae', type='accent'),
        Color(name='greenA400', value='#00e676', type='accent'),
        Color(name='greenA700', value='#00c853', type='accent'),

        Color(name='lightGreenA100', value='#ccff90', type='accent'),
        Color(name='lightGreenA200', value='#b2ff59', type='accent'),
        Color(name='lightGreenA400', value='#76ff03', type='accent'),
        Color(name='lightGreenA700', value='#64dd17', type='accent'),

        Color(name='limeA100', value='#f4ff81', type='accent'),
        Color(name='limeA200', value='#eeff41', type='accent'),
        Color(name='limeA400', value='#c6ff00', type='accent'),
        Color(name='limeA700', value='#aeea00', type='accent'),

        Color(name='yellowA100', value='#ffff8d', type='accent'),
        Color(name='yellowA200', value='#ffff00', type='accent'),
        Color(name='yellowA400', value='#ffea00', type='accent'),
        Color(name='yellowA700', value='#ffd600', type='accent'),

        Color(name='amberA100', value='#ffe57f', type='accent'),
        Color(name='amberA200', value='#ffd740', type='accent'),
        Color(name='amberA400', value='#ffc400', type='accent'),
        Color(name='amberA700', value='#ffab00', type='accent'),

        Color(name='orangeA100', value='#ffd180', type='accent'),
        Color(name='orangeA200', value='#ffab40', type='accent'),
        Color(name='orangeA400', value='#ff9100', type='accent'),
        Color(name='orangeA700', value='#ff6d00', type='accent'),

        Color(name='deepOrangeA100', value='#ff9e80', type='accent'),
        Color(name='deepOrangeA200', value='#ff6e40', type='accent'),
        Color(name='deepOrangeA400', value='#ff3d00', type='accent'),
        Color(name='deepOrangeA700', value='#dd2c00', type='accent'),
    ])


def reverse_func(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0001_initial')
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func),
    ]
