# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-12 23:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=32, unique=True)),
                ('shortName', models.CharField(default='', help_text='Short version of the page name', max_length=16, null=True)),
                ('alias', models.SlugField(editable=False, max_length=32)),
            ],
            options={
                'verbose_name': 'Page',
                'verbose_name_plural': 'Pages',
            },
        ),
        migrations.CreateModel(
            name='PageLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', imagekit.models.fields.ProcessedImageField(default=None, null=True, upload_to='uploads/icons')),
                ('apperance', models.CharField(choices=[('text', 'Just text'), ('button', 'Like a button')], default='text', max_length=255)),
                ('openNewTab', models.BooleanField(default=True, verbose_name='Open this link in a new tab?')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Page')),
            ],
            options={
                'verbose_name': 'Page Link',
                'verbose_name_plural': 'Page Links',
            },
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', imagekit.models.fields.ProcessedImageField(default=None, null=True, upload_to='uploads/icons')),
                ('apperance', models.CharField(choices=[('text', 'Just text'), ('button', 'Like a button')], default='text', max_length=255)),
                ('openNewTab', models.BooleanField(default=True, verbose_name='Open this link in a new tab?')),
                ('name', models.CharField(default='', max_length=255)),
                ('url', models.URLField()),
            ],
            options={
                'verbose_name': 'Social Link',
                'verbose_name_plural': 'Social Links',
            },
        ),
        migrations.CreateModel(
            name='Toolbar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('showPageName', models.BooleanField(default=True)),
                ('icon', imagekit.models.fields.ProcessedImageField(default=None, null=True, upload_to='uploads/icons')),
            ],
            options={
                'verbose_name': 'Toolbar',
                'verbose_name_plural': 'Toolbars',
            },
        ),
        migrations.CreateModel(
            name='ToolbarLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', imagekit.models.fields.ProcessedImageField(default=None, null=True, upload_to='uploads/icons')),
                ('apperance', models.CharField(choices=[('text', 'Just text'), ('button', 'Like a button')], default='text', max_length=255)),
                ('openNewTab', models.BooleanField(default=True, verbose_name='Open this link in a new tab?')),
                ('name', models.CharField(default='', max_length=255)),
                ('shortName', models.CharField(default='', help_text='Short version of the name', max_length=16, null=True)),
                ('url', models.URLField()),
                ('toolbar', models.ManyToManyField(related_name='links', to='api.Toolbar')),
            ],
            options={
                'verbose_name': 'Toolbar Link',
                'verbose_name_plural': 'Toolbar Links',
            },
        ),
        migrations.AddField(
            model_name='page',
            name='toolbar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Toolbar'),
        ),
    ]
