# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-12 21:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='PageLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
                ('icon', imagekit.models.fields.ProcessedImageField(upload_to='uploads/icons')),
                ('apperance', models.CharField(choices=[('text', 'Just text'), ('button', 'Like a button')], default='text', max_length=255)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Page')),
            ],
            options={
                'verbose_name': 'Page Link',
                'verbose_name_plural': 'Page Links',
            },
        ),
    ]
