# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-12 21:21
from __future__ import unicode_literals

from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', imagekit.models.fields.ProcessedImageField(default=None, null=True, upload_to='uploads/icons')),
                ('apperance', models.CharField(choices=[('text', 'Just text'), ('button', 'Like a button')], default='text', max_length=255)),
                ('name', models.CharField(default='', max_length=255)),
                ('url', models.URLField()),
            ],
            options={
                'verbose_name': 'Social Link',
                'verbose_name_plural': 'Social Links',
            },
        ),
        migrations.RemoveField(
            model_name='pagelink',
            name='name',
        ),
        migrations.AlterField(
            model_name='pagelink',
            name='icon',
            field=imagekit.models.fields.ProcessedImageField(default=None, null=True, upload_to='uploads/icons'),
        ),
    ]
