# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-12 21:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20170412_2121'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='page',
            options={'verbose_name': 'Page', 'verbose_name_plural': 'Pages'},
        ),
        migrations.AddField(
            model_name='page',
            name='name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
