# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-13 19:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20170413_1938'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pagelink',
            old_name='apperance',
            new_name='appearance',
        ),
        migrations.RenameField(
            model_name='sociallink',
            old_name='apperance',
            new_name='appearance',
        ),
        migrations.RenameField(
            model_name='toolbarlink',
            old_name='apperance',
            new_name='appearance',
        ),
        migrations.AlterField(
            model_name='toolbar',
            name='name',
            field=models.CharField(blank=True, default=None, help_text='Only visible to you. Use it to manage yours toolbars', max_length=255, null=True),
        ),
    ]
